### REQUISICAO PARA A RAIZ DO PRODUTO
GET http://localhost:5127


### LISTAR PRODUTOS
GET http://localhost:5127/api/produto/listar

### CADASTRAR PRODUTO
POST http://localhost:5127/api/produto/cadastrar/flamengo
